### ISSUE TITLE
clang with libstdc++ in cmake build system

### ISSUE THREAD

**Issue by Bjoe** [pocoproject/poco#1973]
Poco version: 1.8.0
Commit: 6f3aef61d13aeccbae6000500b973726f265a880
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
$ clang++-3.8 -v
clang version 3.8.1-18ubuntu1 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

In the cmake build system I cannot use anymore clang with libstdc++ because of this lines in CMakeLists.txt:74

```
if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
endif()
```

If I comment this line 74, all is fine.

@aleks-f I see in the commit 87ec631b4a374bfe4e6b4731ef90e90d94d13cd2 that you add this lines. Can you remember what was the purpose?

**Comment by aleks-f** [comment]
yes,  I was hitting [this bug](https://sourceware.org/bugzilla/show_bug.cgi?id=13566) on travis because clang uses g++ stdlib unless libc++ explicitly specified
perhaps you can try to detect in cmake which stdlib version is on the build host and select accordingly. I think bug applies only to stdlib accompanying g++ 4.8, but I'm not 100% sure

**Comment by aleks-f** [comment]
alternatively, maybe replace `gets()` - the problem was somewhere in CppUnit, I don't think we use gets in poco

**Comment by Bjoe** [comment]
Hm [this bug in glibc](https://sourceware.org/bugzilla/show_bug.cgi?id=13566) is fixed for all glibc version since 2012-03-06 . Is this really the case?
What is with the "make build" system ? We should also add here libc++ ....  
If when, should we really force to use libc++ for clang? What is with android? They use also clang as compiler but there is no libc++......
I think it will make problems and for me is this more or less a  release blocker.
I will investigate this in  #1975 what was the root cause and try to fix this.

**Comment by aleks-f** [comment]
@Bjoe see error [here](https://travis-ci.org/pocoproject/poco/jobs/292346016#L4798)
started happening after e4b8aa5967fde5942e7e7e1b852951a99b24e52e
fixed with 87ec631b4a374bfe4e6b4731ef90e90d94d13cd2
probably best to get rid of `gets()` IMO

**Comment by Bjoe** [comment]
@aleks-f Unfortunately it is not possible to get rid of gets() ... :-(

I try to fix this in cmake build system.

**Comment by Bjoe** [comment]
Is fixed in #1975 .
I add a "try compile a simple cpp source file" in the "check_for_cxxXX_compiler" macro. But the better approach, I think, is to use [compile-feature-requirements](https://cmake.org/cmake/help/v3.2/manual/cmake-compile-features.7.html?highlight=feature#compile-feature-requirements) from cmake. But this need more effort to implement. Maybe I will do this for 2.x.x 

Btw. I had noted before, what is with Android? 
We have on travis no Android build. But I think it is a good idea to have such a build for Poco. I helped another project to add an Android build on Travis (see [Improve android build in cmake](https://github.com/taocpp/PEGTL/pull/74) )
@zosrothko Can we also add this. I can help there.

**Comment by obiltschnig** [comment]
Yes, having an Android build wound be great. Also one for iOS.

**Comment by zosrothko** [comment]
@Bjoe Add Android build on [Travis ](https://travis-ci.org/Kampbell/poco/jobs/297466292) under Linux on branch develop with
```
cmake -DANDROID_PLATFORM=android-19 -DENABLE_PDF=OFF -DENABLE_TESTS=ON 
```
but CMake does not seems to get it
```
CMake Warning:

  Manually-specified variables were not used by the project:

    ANDROID_PLATFORM
```

**Comment by Bjoe** [comment]
> Yes, having an Android build wound be great.

@Obiltschnig no problem.... :-)

> Also one for iOS.

@Obiltschnig yes that was also nice to have. Maybe I can solve this also but this month not ;-) I have to wait for a colleague ... maybe we need some cmake changes because iOS build the libraries as "framework" bundle.... or is this only for iPhone?!

@zosrothko cmake is claimning about ANDROID_PLATFORM because you are not give cmake a toolchain file.

To build a cmake project for another platform (cross-compiling) you should give cmake a toolchain file via the following parameter:
``
... cmake -DCMAKE_TOOLCHAIN_FILE=/path/to/the/toolchainfile.cmake
``
In the toolchain file there are all specific platform tools configured, for example where to find the compiler for the target platform, the libraries etc.
Google change the buildsystem from make to cmake, so we are lucky to have a already setup toolchain for android :-)

The -DANDROID_PLATFORM=android-19 set the Android API level in the toolchain file.

We should add following lines into travis.yml (maybe I can add this, test and create a pull request?!)
```
    - language: android
      jdk: openjdk8
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-23.0.3
          - extra-android-support
          - extra-android-m2repository
          - android-22
          - sys-img-armeabi-v7a-android-22
          # Unfortunaly travis use the old android sdk tool instead of using the new sdkmanager.
          # In this deprecated android sdk tool there is no ndk-bundle or cmake package!
        licenses:
          - '.+'
      before_install:
        # install NDK and cmake via android sdkmanager. Unfortunaly to acknowledge the licenses 
        # takes a while. Looks like the "echo y" solution is not working. Needs improvement !
        - export TERM=dumb
        - echo "y" | /usr/local/android-sdk/tools/bin/sdkmanager "ndk-bundle" "cmake;3.6.4111459"      
      before_script:
        - export TERM=dumb
        - export _NO_CHECK_SIGNATURE=true
        - echo no | /usr/local/android-sdk/tools/bin/avdmanager create avd -n test -k "system-images;android-22;google_apis;armeabi-v7a"
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      script:
        # Mandatory cmake parameter for the android toolchain:
        # /usr/local/android-sdk/cmake/3.6.4111459/bin/cmake -DANDROID_ABI=armeabi-v7a -DCMAKE_TOOLCHAIN_FILE=/usr/local/android-sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-22
        # See also in /usr/local/android-sdk/ndk-bundle/build/cmake/android.toolchain.cmake
        
        # Using the ninja build command. Is much faster then make build command.
        - mkdir cmake-build && cd cmake-build && /usr/local/android-sdk/cmake/3.6.4111459/bin/cmake -G'Android Gradle - Ninja' -DANDROID_ABI=armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/usr/local/android-sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-22 -DCMAKE_MAKE_PROGRAM=/usr/local/android-sdk/cmake/3.6.4111459/bin/ninja -DENABLE_PDF=OFF -DENABLE_TESTS=ON ..
        - /usr/local/android-sdk/cmake/3.6.4111459/bin/cmake --build . --target all
        - /usr/local/android-sdk/cmake/3.6.4111459/bin/cmake --build . --target test

```
Btw, I used mostly [ninja](https://ninja-build.org/) as "make" command. I faster then make.

I don't know for which API level we should add a test build. On the [Dashboard](https://developer.android.com/about/dashboards/index.html) we can see which API level is mostly used.
